version: '2'
services:
  strapi-postgresql:
    extends:
      file: postgresql.yml
      service: strapi-postgresql
  strapi-registry:
    extends:
      file: jhipster-registry.yml
      service: strapi-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
  strapi-gateway:
    extends:
      file: gateway.yml
      service: strapi-gateway
  strapi-sonar:
    extends:
      file: sonar.yml
      service: strapi-sonar
