version: '2'
services:
  strapi-postgresql:
    image: postgres:latest
    container_name: strapi-postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=strapi
    volumes:
      - ~/volumes/strapi/postgresql/:/var/lib/postgresql/data/
    command: postgres -c listen_addresses='*'
    ports:
      - 5432:5432
